### PR TITLE
Add Lua 5.1 support via lua-compat-5.3

### LINKED ISSUE #1: Feature request: add back Lua 5.1 support
Please consider adding back Lua 5.1 support. You can use the helper files from [lua-compat-5.2](https://github.com/keplerproject/lua-compat-5.2) here for minimal impact on the codebase.

(Also, the `luasyslog` entry in https://luarocks.org is unmaintained (it's stil owned by the `luarocks` fallback account since the luarocks.org migration years ago) -- if you add back Lua 5.1 support we can put your fork in the root manifest as the default one, since other rocks depending on root `luasyslog` expect Lua 5.1 support.

Thank you!

### PR DESCRIPTION
**Pull request by hishamhm**
Adds back Lua 5.1 support through the use of [lua-compat-5.2](https://github.com/keplerproject/lua-compat-5.2).

Addition to the code of luasyslog itself is minimal: `#include "compat-5.2.h"`, which is a no-op in Lua >= 5.2.

(Also fixes a minor issue in the rockspec I encountered, making sure ./autogen.sh is executable once unpacked.)

Closes #1.

### CODE REVIEW

**Comment by ntd** [comment]
Hi @hishamhm, thanks for the feedback: much appreciated.

Unfortunately it does not work with lua 5.3 out of the box.

```
  CC       lsyslog.lo
In file included from lsyslog.c:11:0:
compat-5.2.h:149:6: error: conflicting types for 'lua_rawgetp'
 void lua_rawgetp (lua_State *L, int i, const void *p);
      ^~~~~~~~~~~
In file included from lsyslog.c:7:0:
/usr/include/lua.h:247:14: note: previous declaration of 'lua_rawgetp' was here
 LUA_API int (lua_rawgetp) (lua_State *L, int idx, const void *p);
              ^~~~~~~~~~~
In file included from lsyslog.c:11:0:
compat-5.2.h:153:6: error: conflicting types for 'lua_getuservalue'
 void lua_getuservalue (lua_State *L, int i);
      ^~~~~~~~~~~~~~~~
In file included from lsyslog.c:7:0:
/usr/include/lua.h:252:15: note: previous declaration of 'lua_getuservalue' was here
 LUA_API int  (lua_getuservalue) (lua_State *L, int idx);
               ^~~~~~~~~~~~~~~~
make[1]: *** [Makefile:695: lsyslog.lo] Error 1
make[1]: Leaving directory '/home/nicola/sandbox/luasyslog'
make: *** [Makefile:576: all] Error 2

```

I can wrap the include in an `#ifdef` but, given `lua-compat` seems to be a plug&play library, maybe addressing this issue there is more appropriate. Let me know if I can be of any help on my side.

**Comment by hishamhm** [comment]
@ntd Oops! I thought using lua-compat-5.2 would be sufficient. I updated the PR to use [lua-compat-5.3](http://github.com/keplerproject/lua-compat-5.3), please check it out!

**Comment by ntd** [comment]
@hishamhm No problems with Lua 5.2 and Lua 5.3. Thanks again!
